#! /bin/sh

# Start sxhkd in the background if not already running
pgrep -x sxhkd > /dev/null || sxhkd &

# Set 10 named desktops (I–X) on the current monitor
bspc monitor -d I II III IV V VI VII VIII IX X

# Borders & Gaps
bspc config border_width 5
bspc config window_gap          12
bspc config split_ratio          0.5
bspc config focused_border_color "#F9F9FB"
bspc config normal_border_color "#D2D8E0"
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

# Screen edge padding
bspc config top_padding 45
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

# Configure mouse bindings for manipulating floating windows
bspc config pointer_modifier mod4
bspc config pointer_action2 move
bspc config pointer_action1 resize_side
bspc config pointer_action3 resize_corner

# Application-specific rules
#bspc rule -a <AppClassName> <rule1> <rule2> ...

# Autostart: must be the last command
$HOME/.config/polybar/launch.sh &
picom &
feh --bg-fill ~/Pictures/Wallpapers/Anime/light_blue_neko.png
